name: Container Build

on:
  release:
    types: [published]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: cwaits6/.github/.github/workflows/container-build.yml@fix/remove-top-level-permissions
    with:
      dockerfile: Dockerfile
      platforms: linux/amd64,linux/arm64
