name: PR

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    uses: cwaits6/.github/.github/workflows/dependency-review.yml@fix/remove-top-level-permissions
  trivy:
    uses: cwaits6/.github/.github/workflows/trivy.yml@fix/remove-top-level-permissions
  semgrep:
    uses: cwaits6/.github/.github/workflows/semgrep.yml@fix/remove-top-level-permissions
    permissions:
      contents: write
      issues: write
      pull-requests: write
